'use strict';
// Remote MCP servers anyone can add in one click. id is the name the server is
// added under, icon a simple-icons export name. auth 'oauth' servers sign in
// through the browser, and each supports dynamic client registration, which
// mcp-remote needs; 'none' servers answer without any sign-in. 'token' servers
// take a token instead: the one token.cli hands out when you are signed in to
// it, or one you paste, made at token.create.

const MCP_GALLERY = [
  { id: 'notion', name: 'Notion', auth: 'oauth', icon: 'siNotion', url: 'https://mcp.notion.com/mcp',
    description: 'Search, read and update pages and databases in your Notion workspace.' },
  { id: 'linear', name: 'Linear', auth: 'oauth', icon: 'siLinear', url: 'https://mcp.linear.app/mcp',
    description: 'Find, create and update issues and projects in Linear.' },
  { id: 'atlassian', name: 'Jira and Confluence', auth: 'oauth', icon: 'siAtlassian', url: 'https://mcp.atlassian.com/v1/mcp',
    description: 'Look up and edit Jira tickets and Confluence pages.' },
  { id: 'sentry', name: 'Sentry', auth: 'oauth', icon: 'siSentry', url: 'https://mcp.sentry.dev/mcp',
    description: 'Look into the errors and crashes Sentry has caught in your apps.' },
  { id: 'stripe', name: 'Stripe', auth: 'oauth', icon: 'siStripe', url: 'https://mcp.stripe.com',
    description: 'Check payments, customers and invoices in your Stripe account.' },
  { id: 'supabase', name: 'Supabase', auth: 'oauth', icon: 'siSupabase', url: 'https://mcp.supabase.com/mcp',
    description: 'Query and manage the databases in your Supabase projects.' },
  { id: 'canva', name: 'Canva', auth: 'oauth', icon: null, url: 'https://mcp.canva.com/mcp',
    description: 'Find, create and edit designs in your Canva account.' },
  { id: 'intercom', name: 'Intercom', auth: 'oauth', icon: 'siIntercom', url: 'https://mcp.intercom.com/mcp',
    description: 'Search customer conversations and contacts in Intercom.' },
  { id: 'paypal', name: 'PayPal', auth: 'oauth', icon: 'siPaypal', url: 'https://mcp.paypal.com/mcp',
    description: 'Create invoices and look up payments in your PayPal business account.' },
  { id: 'huggingface', name: 'Hugging Face', auth: 'oauth', icon: 'siHuggingface', url: 'https://huggingface.co/mcp?login',
    description: 'Search AI models, datasets and demos on Hugging Face.' },
  { id: 'square', name: 'Square', auth: 'oauth', icon: 'siSquare', url: 'https://mcp.squareup.com/sse', type: 'sse',
    description: 'Check sales, orders, customers and stock in your Square account.' },
  { id: 'webflow', name: 'Webflow', auth: 'oauth', icon: 'siWebflow', url: 'https://mcp.webflow.com/mcp',
    description: 'Edit the pages and content of your Webflow sites.' },
  { id: 'wix', name: 'Wix', auth: 'oauth', icon: 'siWix', url: 'https://mcp.wix.com/mcp',
    description: 'Manage your Wix sites, from pages to products and bookings.' },
  { id: 'airtable', name: 'Airtable', auth: 'oauth', icon: 'siAirtable', url: 'https://mcp.airtable.com/mcp',
    description: 'Read and update the records in your Airtable bases.' },
  { id: 'clickup', name: 'ClickUp', auth: 'oauth', icon: 'siClickup', url: 'https://mcp.clickup.com/mcp',
    description: 'Find, create and update tasks and docs in ClickUp.' },
  { id: 'zapier', name: 'Zapier', auth: 'oauth', icon: 'siZapier', url: 'https://mcp.zapier.com/api/mcp/mcp',
    description: 'Take actions in the thousands of apps you have connected to Zapier.' },
  { id: 'jam', name: 'Jam', auth: 'oauth', icon: null, url: 'https://mcp.jam.dev/mcp',
    description: 'Read the bug reports, recordings and logs captured with Jam.' },
  { id: 'netlify', name: 'Netlify', auth: 'oauth', icon: 'siNetlify', url: 'https://netlify-mcp.netlify.app/mcp',
    description: 'Create, deploy and manage your websites on Netlify.' },
  { id: 'neon', name: 'Neon', auth: 'oauth', icon: 'siNeon', url: 'https://mcp.neon.tech/mcp',
    description: 'Create and query the Postgres databases in your Neon account.' },
  { id: 'prisma', name: 'Prisma', auth: 'oauth', icon: 'siPrisma', url: 'https://mcp.prisma.io/mcp',
    description: 'Create and manage Prisma Postgres databases.' },
  { id: 'github', name: 'GitHub', auth: 'token', icon: 'siGithub', url: 'https://api.githubcopilot.com/mcp/',
    description: 'Work with the issues, pull requests, code and repositories on GitHub.',
    token: { cli: 'gh', login: 'gh auth login', create: 'https://github.com/settings/personal-access-tokens/new' } },
  { id: 'gitlab', name: 'GitLab', auth: 'oauth', icon: 'siGitlab', url: 'https://gitlab.com/api/v4/mcp',
    description: 'Work with the issues, merge requests and code in your GitLab projects.' },
  { id: 'granola', name: 'Granola', auth: 'oauth', icon: null, url: 'https://mcp.granola.ai/mcp',
    description: 'Search the notes and transcripts of your meetings in Granola.' },
  { id: 'todoist', name: 'Todoist', auth: 'oauth', icon: 'siTodoist', url: 'https://ai.todoist.net/mcp',
    description: 'Add, update and complete tasks in your Todoist lists.' },
  { id: 'miro', name: 'Miro', auth: 'oauth', icon: 'siMiro', url: 'https://mcp.miro.com/',
    description: 'Read and add to the boards in your Miro workspace.' },
  { id: 'posthog', name: 'PostHog', auth: 'oauth', icon: 'siPosthog', url: 'https://mcp.posthog.com/mcp',
    description: 'Ask questions about how people use your product, answered from PostHog.' },
  { id: 'dropbox', name: 'Dropbox', auth: 'oauth', icon: 'siDropbox', url: 'https://mcp.dropbox.com/mcp',
    description: 'Search and read the files in your Dropbox.' },
  { id: 'cloudflare-docs', name: 'Cloudflare docs', auth: 'none', icon: 'siCloudflare', url: 'https://docs.mcp.cloudflare.com/mcp',
    description: 'Look up answers in the Cloudflare documentation.' },
  { id: 'context7', name: 'Context7', auth: 'none', icon: null, url: 'https://mcp.context7.com/mcp',
    description: 'Fetch up-to-date documentation for the code libraries you use.' },
  { id: 'deepwiki', name: 'DeepWiki', auth: 'none', icon: null, url: 'https://mcp.deepwiki.com/mcp',
    description: 'Ask questions about any public GitHub project and get answers from its code.' },
  { id: 'exa', name: 'Exa', auth: 'none', icon: null, url: 'https://mcp.exa.ai/mcp',
    description: 'Search the web and read pages to find current information.' },
];

module.exports = { MCP_GALLERY };
